### ISSUE TITLE
'edge cases'

### ISSUE THREAD

**Issue by rachaelcodes** [AbdullahChaudhry/fizzbuzz#2]
This is great, lots of detail and will guide students through the process. Just one bit of terminology - I think the phrase 'edge cases' refers to the absolute extremes (maximums and minimums) rather than the standard 'is divisible by 5'.

**Comment by AbdullahChaudhry** [comment]
You're right. Will bear this in mind and make any adjusted if needed. Thanks : )

**Comment by AbdullahChaudhry** [comment]
Closing as edge cases has now been removed from the readme
